
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: webapi-example
  name: webapi-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: webapi-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapi-example
    spec:
      containers:
      - image: capita.azurecr.io/sample/webapp:00
        name: webapicontainer
        ports:
        - containerPort: 80
       


